add_newline = false
command_timeout = 1000

format = '''
$username $directory$git_branch $nodejs $character
[Œª](bold green) '''

[character]
success_symbol = ""
error_symbol = "üî• "

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ Û±ëç $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = '[$duration](bold yellow)'

# ---

[username]
format='[$user]($style)'
show_always = true
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
# truncation_length = 3
# truncate_to_repo = true
# fish_style_pwd_dir_length=2
home_symbol = 'Û∞ãú ~'
# read_only_style = '197'
# read_only = ' ÔÄ£ '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = 'ÓÇ†'
format = '[$symbol $branch]($style)'
# truncation_length = 4
# truncation_symbol = '‚Ä¶/'
style = 'bold green'

# Shows current git status
[git_status]
disabled = true

[nodejs]
format = "via [Û∞éô $version](bold green) "
disabled = false